# Generated by Django 3.2.19 on 2023-09-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lx_pathway_plugin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pathway',
        ),
    ]
